

name: Docker #opcional

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest #opcional
    steps:
    - uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0
    
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ vars.USER_DOCKER_HUB}}
        password: ${{ secrets.PASS_DOCKER_HUB }}
                